### ISSUE TITLE
Forge loads HomeSweetHome before it loads KatLib

### ISSUE THREAD

**Issue by K4N0** [Katrix-/HomeSweetHome#1]
I can't startup my server with this plugin.
http://pastebin.com/2Xg4DEJy

**Comment by Katrix** [comment]
My guess is that this does not happen when only loading KatLib and not HomeSweetHome?

**Comment by K4N0** [comment]
i haven't tried that, sec

Edit: KatLib-5.0.0-assembly-1.0.2 It does not crash the server when running KatLib on the server. It only crashes when i try to run HomeSweetHome.

**Comment by Katrix** [comment]
Try this and tell me if it works.
https://github.com/Katrix-/HomeSweetHome/releases/tag/1.0.1

**Comment by K4N0** [comment]
testing right now.
Edit: Still crashes
http://pastebin.com/dTj9ieFK

**Comment by Katrix** [comment]
Until I find a better solution to fix this, just ... throw yet another z at the beggining of homeSweetHome's file name.

**Comment by K4N0** [comment]
I do that to separate mods and plugins. that would be funny if that was the cause of the crash.
Did you want full logs?
Edit: Same crash with the zz removed.
Edit log files. I think this works
https://www.dropbox.com/sh/zaoe7lbightlhk2/AACC6JGdmUkBrEU7y7DGBgsya?dl=1

**Comment by Katrix** [comment]
I don't want you to remove them, I want you to add yet another z at the beginning of HomeSweetHome's jarfile (so that it's zzz instead of zz). Just make sure that if sorted alphabetically, it's below KatLib.

**Comment by K4N0** [comment]
I thought you were being sarcastic. I can't believe that actually worked. Thanks,

**Comment by K4N0** [comment]
I'm having trouble overiding EssentialCmds plugin of /home. What is homesweethome plugin id?
homesweethome : HomeSweetHome : homesweethome/homesweethome :

**Comment by K4N0** [comment]
So i removed all other plugins and just left kat and homesweethome. i made sure homesweethome was below kat. It didn't crash, but i also can't get the command /home to work. i have tried /help and i don't see the command at all. I have tried /home set with no results.

**Comment by Katrix** [comment]
Is there any other exception saying something like "NoSuchMethodError: HoconConfigurationLoader.Builder.setRenderOptions"?

**Comment by K4N0** [comment]
I'll check when i get home. I'll delete all the log files and run the server with only kat and homesweethome.
I'll try all the commands and see if anything posts in console. i'll shut down the server and upload all of the logs to see if anything useful comes from it.
