### ISSUE TITLE
Player homes being merged

### ISSUE THREAD

**Issue by Kaelico** [Katrix-/HomeSweetHome#2]
Player 1 uses /home set Test1
Player 2 uses /home list and can see Test1

**Comment by Katrix** [comment]
That's a sneaky bug. I think I know where the problem lord though. I'll probably create a new release with a fix for this and some other stuff.

**Comment by Kaelico** [comment]
Any idea when you'll release version 2.0.1? Currently don't have a home system since everyone loves your mod, but it's kind of impossible to use due to the homes being merged ha ha.

**Comment by Katrix** [comment]
Yeah, I can see that. I released an update a few hours ago. https://ore.spongepowered.org/Katrix/HomeSweetHome/versions

**Comment by Kaelico** [comment]
Never knew that page existed o-o
I appreciate the fix. If we find anything else I'll let you know
