### ISSUE TITLE
Home Invites/Accepts

### ISSUE THREAD

**Issue by Kaelico** [Katrix-/HomeSweetHome#3]
Player1 uses /home set Test1 then /home invite Player2 Test1
Player2 receives two errors
Error 1 - Message shows "You have been invited to "Test1" by Player2(Instead of Player1)
Error 2 - When using /home goto Player1 Test1 receives error "A home with that name was not found"

Minecraft 1.10.2
Forge 12.18.3.2215
Sponge 5.1.0 Beta 2039
HomeSweetHome 2.0.1

**Comment by Katrix** [comment]
Okay fixed these and a bunch of other stuff. New release is up. Sorry for not catching these myself. I can test the plugin but I can't see the bugs that require more than one person as that's all I am.
