### ISSUE TITLE
Request Teleport (Goto)

### ISSUE THREAD

**Issue by Kaelico** [Katrix-/HomeSweetHome#4]
We found another home invite bug. Thanks for the updates

Player1 uses /home invite player2 Test
Player2 uses /home goto Player1 Test
Player1 uses /home accept Player2 and receives the message "That player has not sent a home request"

Minecraft 1.10.2
Forge 12.18.3.2215
Sponge 5.1.0 Beta 2059
HomeSweetHome 2.0.2

EDIT: Tested goto with people added to the resident and that works perfectly. It's only home accept that is broken now.

**Comment by Katrix** [comment]
At first I thought this was an interesting bug, but it wasn't both invites and requests were just borked. Originally I didn't think of pushing a new build for this, but invites and requests not working is kind of a big thing.
