### ISSUE TITLE
[Suggestion] /sethome prompt

### ISSUE THREAD

**Issue by yepidoodles** [Katrix-/HomeSweetHome#5]
Most of my players think they can't set homes because they always use /sethome, it would be great if you could add it so that when players do /sethome, it tells them to do /home set :)

Thanks

- Alice

**Comment by Katrix** [comment]
I am open to making it easier to understand what command are available, but I feel a specific prompt for `/sethome` would be a bit to specific, and wouldn't solve the overall problem of plays not finding their way to `/home list` where most common operations are listed as buttons that suggest the appropriate command. Would a better idea be to make `/home` with no arguments an alias for `/home list`? That way they can see the set home button and learn the command to use.

**Comment by yepidoodles** [comment]
Would be a good idea for `/home` as an alias for `/home list`. Make `/sethome` an alias for it too, if you want.
People are so used to using `/sethome` from Essentials, from 1.7.10 and from vanilla Spigot servers, they don't consider there's another option.

**Comment by Katrix** [comment]
Fixed. `/home` and `/homes` now both route to `/home list` New version will be released soon.
