### ISSUE TITLE
Home plugin not working

### ISSUE THREAD

**Issue by MGKPartyBoy** [Katrix-/HomeSweetHome#7]
I have the plugin HomeSweetHome installed on my server...
There is no errors when starting or no errors when doing commands, however, if I do, for example, /sethome home  and then try to do /home home it'll say "You don't have any homes"

I have the the latest version of HomeSweetHome (6.0). I have given the default rank the permission to use all the home commands. 
homesweethome.home.tp Allows a player to use /home
homesweethome.home.set Allows a player to use /home set
homesweethome.home.remove Allows a player to use /home remove
homesweethome.home.list Allows a player to use /home list
homesweethome.home.limit Allows a player to use /home limit
homesweethome.home.invite Allows a player to use /home invite
homesweethome.home.goto Allows a player to use /home goto
homesweethome.home.accept Allows a player to use /home accept

It let's us use the commands but it doesn't let us go to our homes. If I would try to re-set the home "home" it would say "You already have a home by that name" but it won't let us teleport to it. It also doesn't bring up the home in the /home GUI

Permission Plugin: LuckPerms

**Comment by Katrix** [comment]
Are you using `/sethome <home>` or `/home set <home>`? HomeSweetHome uses the second one.

**Comment by MGKPartyBoy** [comment]
./sethome home

**Comment by Katrix** [comment]
As said, HomeSweetHome uses `/home set <home>`. Try that and see if it works.

**Comment by MGKPartyBoy** [comment]
That works... I thought it used /sethome

Sorry to bug you! :)
