### ISSUE TITLE
1.12.1 Version?

### ISSUE THREAD

**Issue by yepidoodles** [Katrix-/HomeSweetHome#9]
Hello,

Today I started a 1.12.1 test server, I know that HomeSweetHome doesn't currently have 1.12.1 version and I've been using this plugin since I updated to 1.10.2 so I really hope you're able to update this :)

I tried using the latest version with SpongeForge 1.12.1-2480-7.0.0-BETA-2629, but got a startup error, thought it might be useful :) 

[![Screenshot from Gyazo](https://gyazo.com/ce02c4166272e4b3e186872727aadd1a/raw)](https://gyazo.com/ce02c4166272e4b3e186872727aadd1a)
Sorry that it's a screenshot, there's something wrong with my forge logs so I wasn't able to get a text version.

Many thanks,

Alice

**Comment by Katrix** [comment]
I've been naughty, and now I pay the price D:.

For now downgrade to KatLib 2.2. Localization shouldn't be there, so neither should the bug. I think it should still be compatible with API 6.0.0, so you can use that one.

**Comment by Katrix** [comment]
Fixed Download 2.3.1 of KatLib

**Comment by yepidoodles** [comment]
Thank you very much, I'll give it a try shortly :)
